source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'BSGMetrics_Example' do
  use_frameworks!

  pod 'BSGMetrics', :path => '../'
  pod 'BSGUtilities'

  target 'BSGMetrics_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
