source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'BSGMetrics_Example' do
  use_frameworks!

  pod 'BSGMetrics', :path => '../'
  pod 'BSGUtilities', :git => 'https://github.com/dirtyhenry/BSGUtilities', :branch => 'main'

  target 'BSGMetrics_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end