use_frameworks!

target 'BSGMetrics_Example' do
  pod 'BSGMetrics', :path => '../'
  pod 'BSGUtilities', :git => 'https://github.com/Bootstragram/BSGUtilities.git'

  target 'BSGMetrics_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
