# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
- bundle install
- bundle exec pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/BSGMetrics.xcworkspace -scheme BSGMetrics-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
